language: php

php:
  - '7.2'
  - '7.1'

env:
  - DB=sqlite3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text

matrix:
  allow_failures:
    - php: 7.2
    - php: hhvm
  fast_finish: true

after_success:
    - bash <(curl -s https://codecov.io/bash)